=== NEU-Libraries/cerberus/jetty/fedora/default/server/xsd/beSecurity.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="info:fedora/fedora-system:def/beSecurity#" xmlns="info:fedora/fedora-system:def/beSecurity#" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:element name="serviceSecurityDescription" type="serviceSecurityDescriptionType"/>
	<xsd:complexType name="serviceSecurityDescriptionType">
		<xsd:sequence>
			<xsd:element name="serviceSecurityDescription" type="serviceSecurityDescriptionType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="role" type="xsd:string" use="required"/>
		<xsd:attribute name="callSSL" type="xsd:boolean" default="false"/>
		<xsd:attribute name="callBasicAuth" type="xsd:boolean" default="false"/>
		<xsd:attribute name="callUsername" type="xsd:string" use="optional"/>
		<xsd:attribute name="callPassword" type="xsd:string" use="optional"/>
		<xsd:attribute name="callbackSSL" type="xsd:boolean" default="false"/>
		<xsd:attribute name="callbackBasicAuth" type="xsd:boolean" default="false"/>
		<xsd:attribute name="iplist" type="xsd:string" use="optional"/>
		<xsd:anyAttribute namespace="##other" processContents="lax"/>
	</xsd:complexType>
</xsd:schema>

=== NEU-Libraries/cerberus/jetty/fedora/default/server/fedora-internal-use/config/beSecurity-secure-all.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- callSSL, callBasicAuth, callUsername, callPassword callbackSSL, callbackBasicAuth, iplist-->
<serviceSecurityDescription role="default" 
xmlns="info:fedora/fedora-system:def/beSecurity#" 
callSSL="false" callbackSSL="false" callBasicAuth="false" callbackBasicAuth="false" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="info:fedora/fedora-system:def/beSecurity# 
http://www.fedora.info/definitions/1/0/api/beSecurity.xsd">
    <serviceSecurityDescription role="fedoraInternalCall-1" callBasicAuth="true" callSSL="true" callbackBasicAuth="true" callbackSSL="true" callUsername="fedoraIntCallUser" callPassword="changeme" iplist="127.0.0.1"/>
    <serviceSecurityDescription role="fedoraInternalCall-2" callBasicAuth="false" callSSL="false" callbackBasicAuth="false" callbackSSL="false" iplist="127.0.0.1"/>
	<serviceSecurityDescription role="demo:2" iplist="127.0.0.1"/>
	<serviceSecurityDescription role="demo:2/getThumbnail" iplist="127.0.0.1"/>	
	<serviceSecurityDescription role="demo:3" iplist="128.143.22.236"/>
	<serviceSecurityDescription role="demo:4" iplist="128.143.22.200"/>
	<serviceSecurityDescription role="demo:9" iplist="128.143.22.200"/>
	<serviceSecurityDescription role="demo:13" iplist="127.0.0.1"/>
	<serviceSecurityDescription role="demo:16" iplist="128.143.22.236"/>
	<serviceSecurityDescription role="demo:20" iplist="127.0.0.1"/>
	<serviceSecurityDescription role="demo:25" iplist="127.0.0.1"/>
	<serviceSecurityDescription role="demo:28" iplist="128.143.22.200"/>
	<serviceSecurityDescription role="demo:DualResImageCollection" iplist="127.0.0.1"/>
	<serviceSecurityDescription role="demo:DualResImageImpl" iplist="127.0.0.1"/>
</serviceSecurityDescription>
