=== NEU-Libraries/cerberus/jetty/fedora/test/server/xsd/foxml1-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--***********************************************************************-->
<!-- TITLE       : FOXML 1.1 XSD Schema                                    -->
<!-- DESCRIPTION : This document expresses the basic structure and         -->
<!--               constraints for objects encoded in FOXML 1.1.           -->
<!--               This schema, when combined with the FOXML 1.1           -->
<!--               Schematron Rules, can be used to fully validate         -->
<!--               a FOXML 1.1 XML document.                               -->
<!-- CHANGELOG   : (1.0 to 1.1)                                            -->
<!--               o Added a required VERSION attribute to the root        -->
<!--                 element, which must have a value of "1.1".            -->
<!--               o Removed disseminator-related elements (disseminator   -->
<!--                 elements have been removed from the FOXML format      -->
<!--                 due to the CMA).                                      -->
<!--               o Removed #contentModel property (As of Fedora 3.0,     -->
<!--                 content model is asserted via RELS-EXT predicate,     -->
<!--                 fedora-model:hasContentModel                          -->
<!--               o Removed rdf:type property, since typeness is          -->
<!--                 determined by the content model(s)                    -->
<!--***********************************************************************-->
<xsd:schema targetNamespace="info:fedora/fedora-system:def/foxml#" xmlns="info:fedora/fedora-system:def/foxml#" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- the root element for FOXML: digitalObject -->
	<xsd:element name="digitalObject">
		<xsd:annotation>
			<xsd:documentation/>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="digitalObjectType"/>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<!-- complex type declarations -->
	<xsd:complexType name="digitalObjectType">
		<xsd:sequence>
			<xsd:element name="objectProperties" type="objectPropertiesType"/>
			<xsd:element name="datastream" type="datastreamType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="VERSION" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="1.1"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
		<xsd:attribute name="PID" type="pidType" use="optional"/>
		<xsd:attribute name="FEDORA_URI" type="xsd:anyURI" use="optional"/>
		<xsd:anyAttribute namespace="##other" processContents="lax"/>
	</xsd:complexType>
	<xsd:complexType name="objectPropertiesType">
		<xsd:sequence>
			<xsd:element name="property" type="propertyType" maxOccurs="unbounded"/>
			<xsd:element name="extproperty" type="extpropertyType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="datastreamType">
		<xsd:sequence>
			<xsd:element name="datastreamVersion" type="datastreamVersionType" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="ID" type="idType" use="required"/>
		<xsd:attribute name="CONTROL_GROUP" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="E"/>
					<xsd:enumeration value="M"/>
					<xsd:enumeration value="R"/>
					<xsd:enumeration value="X"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="FEDORA_URI" type="xsd:anyURI" use="optional"/>
		<xsd:attribute name="STATE" type="stateType" use="optional"/>
		<xsd:attribute name="VERSIONABLE" type="xsd:boolean" use="optional" default="true"/>
	</xsd:complexType>
	<xsd:complexType name="datastreamVersionType">
		<xsd:sequence>
			<xsd:element name="contentDigest" type="contentDigestType" minOccurs="0"/>
			<xsd:choice>
				<xsd:element name="xmlContent" type="xmlContentType"/>
				<xsd:element name="contentLocation" type="contentLocationType"/>
				<xsd:element name="binaryContent" type="xsd:base64Binary"/>
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="ID" type="idType" use="required"/>
		<xsd:attribute name="LABEL" type="xsd:string" use="optional"/>
		<xsd:attribute name="CREATED" type="xsd:dateTime" use="optional"/>
		<xsd:attribute name="MIMETYPE" type="xsd:string" use="required"/>
		<xsd:attribute name="ALT_IDS" type="uriListType" use="optional"/>
		<xsd:attribute name="FORMAT_URI" type="xsd:anyURI" use="optional"/>
		<xsd:attribute name="SIZE" type="xsd:long" use="optional" default="0"/>
	</xsd:complexType>
	<xsd:complexType name="contentDigestType">
		<xsd:attribute name="TYPE" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="MD5"/>
					<xsd:enumeration value="SHA-1"/>
					<xsd:enumeration value="SHA-256"/>
					<xsd:enumeration value="SHA-384"/>
					<xsd:enumeration value="SHA-512"/>
					<xsd:enumeration value="HAVAL"/>
					<xsd:enumeration value="TIGER"/>
					<xsd:enumeration value="WHIRLPOOL"/>
					<xsd:enumeration value="DISABLED"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="DIGEST" type="xsd:string" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="xmlContentType">
		<xsd:sequence>
			<xsd:any namespace="##any" processContents="skip" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="contentLocationType">
		<xsd:attribute name="TYPE" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="INTERNAL_ID"/>
					<xsd:enumeration value="URL"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="REF" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:anyURI">
					<xsd:minLength value="1"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="propertyType">
		<xsd:attribute name="NAME" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="info:fedora/fedora-system:def/model#state"/>
					<xsd:enumeration value="info:fedora/fedora-system:def/model#label"/>
					<xsd:enumeration value="info:fedora/fedora-system:def/model#createdDate"/>
					<xsd:enumeration value="info:fedora/fedora-system:def/view#lastModifiedDate"/>
					<xsd:enumeration value="info:fedora/fedora-system:def/model#ownerId"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="VALUE" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="extpropertyType">
		<xsd:attribute name="NAME" type="xsd:string" use="required"/>
		<xsd:attribute name="VALUE" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:simpleType name="stateType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="A"/>
			<xsd:enumeration value="D"/>
			<xsd:enumeration value="I"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- See http://www.fedora.info/definitions/identifiers/ -->
	<xsd:simpleType name="pidType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="64"/>
			<xsd:pattern value="([A-Za-z0-9]|-|\.)+:(([A-Za-z0-9])|-|\.|~|_|(%[0-9A-F]{2}))+"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="idType">
		<xsd:restriction base="xsd:ID">
			<xsd:maxLength value="64"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="uriListType">
		<xsd:list itemType="xsd:anyURI"/>
	</xsd:simpleType>
</xsd:schema>

=== NEU-Libraries/cerberus/jetty/fedora/client/demo/batch-demo/foxml-template.xml
<?xml version="1.0" encoding="UTF-8"?>
<foxml:digitalObject VERSION="1.1" PID="template:objectPid" xmlns:foxml="info:fedora/fedora-system:def/foxml#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="info:fedora/fedora-system:def/foxml# http://www.fedora.info/definitions/1/0/foxml1-1.xsd">
	<foxml:objectProperties>
		<foxml:property NAME="info:fedora/fedora-system:def/model#state" VALUE="Active"/>
		<foxml:property NAME="info:fedora/fedora-system:def/model#label" VALUE="template:Object Label"/>
		<foxml:property NAME="info:fedora/fedora-system:def/model#ownerId" VALUE="fedoraAdmin"/>
		<!-- Note: The value for createdDate is assigned dynamically by the Fedora server at ingest time if the createdDate property is not      -->
		<!-- present in the object being ingested. Therefore, it is recommended that this property be omitted from the object template so this   -->
		<!-- date will be assigned dynamically by the Fedora server. If included in the template file, this value will be carried through to the        -->
		<!-- built objects and will result in the specified static date being used at ingest time by the Fedora server rather than dynamically         -->
		<!-- assigning createdDate at ingest time. The same is true for object components like datastreams and disseminators. The                -->
		<!-- datastreamVersion and disseminatorVersion elements contain an optional CREATED attribute that defines a createdDate for     -->
		<!-- these components. If the CREATED attribute is omitted, a createdDate is assinged dynamically at ingest time. If included in the   -->
		<!-- template object, the specified values will be carried through to all built objects resulting in the specified static dates being used     -->
		<!-- rather than than the Fedora server assigning component createdDates.                                                                                                   -->
		<!--                                                                                                                                                                                                                              -->
		<!-- Uncomment the next line only if you want all objects built with this template to retain the specified creation date after ingest.            -->
		<!-- <foxml:property NAME="info:fedora/fedora-system:def/model#createdDate" VALUE="2005-03-15T12:57:07.241Z"/>                   -->
		<foxml:property NAME="info:fedora/fedora-system:def/view#lastModifiedDate" VALUE="2005-03-15T12:57:07.702Z"/>
	</foxml:objectProperties>
	<foxml:datastream CONTROL_GROUP="X" ID="DC" STATE="A" VERSIONABLE="true">
		<!-- Note: The value for createdDate is assigned dynamically by the Fedora server at ingest time if the CREATED attribute is not        -->
		<!-- present on the component in the object being ingested. Therefore, it is recommended that this attribute be omitted from the          -->
		<!-- object template so this date will be assigned dynamically by the Fedora server. If included in the template file, this value will be    -->
		<!-- carried through to the built objects and will result in the specified static date being used at ingest time by the Fedora server          -->
		<!-- rather than dynamically assigning createdDate at ingest time.                                                                                                                   -->
		<!--                                                                                                                                                                                                                             -->
		<!-- Uncomment the the following line if you want the DC datastream for all abjects built with this template to retain the specified         -->
		<!-- createdDate after ingest.                                                                                                                                                                                -->
		<!-- <foxml:datastreamVersion CREATED="2005-03-15T12:57:07.241Z" ID="DC.0" LABEL="template: Dublin Core Record for this object" MIMETYPE="text/xml"> -->
		<foxml:datastreamVersion FORMAT_URI="http://www.openarchives.org/OAI/2.0/oai_dc/" ID="DC.0" LABEL="template: Dublin Core Record for this object" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="DESC" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="DESC.0" LABEL="template: UVA descriptive metadata" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="E" ID="DS1" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="DS1.0" LABEL="template: THUMBNAIL jpg image" MIMETYPE="image/jpeg" SIZE="0">
			<foxml:contentLocation REF="url of THUMBNAIL image" TYPE="URL"/>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="DIGIPROV1" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="DIGIPROV1.0" LABEL="template: UVA digiprov metadata for THUMBNAIL res image" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="SOURCE1" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="SOURCE1.0" LABEL="template: UVA source metadata for THUMBNAIL res image" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="TECH1" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="TECH1.0" LABEL="template: UVA technical metadata for THUMBNAIL image" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="RIGHTS1" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="RIGHTS1.0" LABEL="template: UVA access rights/policy metadata for THUMBNAIL res image" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="E" ID="DS2" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="DS2.0" LABEL="template: MEDIUM res jpg image" MIMETYPE="image/jpeg">
			<foxml:contentLocation REF="template: url of MEDIUM res jpg image" TYPE="URL"/>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="DIGIPROV2" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="DIGIPROV2.0" LABEL="template: UVA digiprov metadata for MEDRES res image" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="SOURCE2" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="SOURCE2.0" LABEL="template: UVA source metadata for MEDIUM res image" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="TECH2" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="TECH2.0" LABEL="template: UVA technical metadata for MED res image" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="RIGHTS2" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="RIGHTS2.0" LABEL="template: UVA access rights/policy metadata for MEDRES res image" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="E" ID="DS3" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="DS3.0" LABEL="template: HIGH res jpg image" MIMETYPE="image/jpeg">
			<foxml:contentLocation REF="template: url of HIGH res jpg image" TYPE="URL"/>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="DIGIPROV3" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="DIGIPROV3.0" LABEL="template: UVA digiprov metadata for HIGH res image" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="SOURCE3" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="SOURCE3.0" LABEL="template: UVA source metadata for HIGH res image" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="TECH3" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="TECH3.0" LABEL="template: UVA technical metadata for HIGH res image" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="RIGHTS3" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="RIGHTS3.0" LABEL="template: UVA access rights/policy metadata for HIGHRES res image" MIMETYPE="text/xml">
			<foxml:xmlContent>
				<dummy/>
			</foxml:xmlContent>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="E" ID="DS4" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="DS4.0" LABEL="template: VERYHIGH jpg image" MIMETYPE="image/jpeg" SIZE="0">
			<foxml:contentLocation REF="template: url of VERYHIGH jpg image" TYPE="URL"/>
		</foxml:datastreamVersion>
	</foxml:datastream>
	<foxml:datastream CONTROL_GROUP="X" ID="DIGIPROV4" STATE="A" VERSIONABLE="true">
		<foxml:datastreamVersion ID="DIGIPROV4.0" LABEL="template: UVA digiprov metadata for VERYHIGH res image" MIMETYPE="text/xml">
			<foxml:xmlContent>
